## Download Dataset from Kaggle

In [1]:
# source: https://www.kaggle.com/discussions/general/74235
from google.colab import userdata
import os

os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')

!kaggle datasets download -d crowdflower/twitter-user-gender-classification

! unzip "twitter-user-gender-classification.zip"

Dataset URL: https://www.kaggle.com/datasets/crowdflower/twitter-user-gender-classification
License(s): CC0-1.0
Downloading twitter-user-gender-classification.zip to /content
  0% 0.00/3.02M [00:00<?, ?B/s]
100% 3.02M/3.02M [00:00<00:00, 608MB/s]
Archive:  twitter-user-gender-classification.zip
  inflating: gender-classifier-DFE-791531.csv

In [6]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# we'll want this for plotting
import matplotlib.pyplot as plt

# we'll want this for text manipulation
import re

# for quick counting
from collections import defaultdict

# the Naive Bayes model
from sklearn.naive_bayes import MultinomialNB                # Classifier
from sklearn.model_selection import train_test_split
# function for transforming documents into counts
from sklearn.feature_extraction.text import CountVectorizer  # Vectorizer
# function for encoding categories
from sklearn.preprocessing import LabelEncoder

# have to use latin1 even though it results in a lot of dead characters
twigen = pd.read_csv("gender-classifier-DFE-791531.csv", encoding='latin1')
twigen.head()

    _unit_id  _golden  ...   tweet_location               user_timezone
0  815719226    False  ...  main; @Kan1shk3                     Chennai
1  815719227    False  ...              NaN  Eastern Time (US & Canada)
2  815719228    False  ...           clcncl                    Belgrade
3  815719229    False  ...    Palo Alto, CA  Pacific Time (US & Canada)
4  815719230    False  ...              NaN                         NaN

[5 rows x 26 columns]

In [7]:
# a.k.a Preprocessing
def normalize_text(s):
    # just in case
    s = str(s)
    s = s.lower()

    # remove punctuation that is not word-internal (e.g., hyphens, apostrophes)
    s = re.sub('\s\W',' ',s)
    s = re.sub('\W\s',' ',s)

    # make sure we didn't introduce any double spaces
    s = re.sub('\s+',' ',s)

    return s

twigen['text_norm'] = [normalize_text(s) for s in twigen['text']]
twigen['description_norm'] = [normalize_text(s) for s in twigen['description']]

<>:8: SyntaxWarning: invalid escape sequence '\s'
<>:9: SyntaxWarning: invalid escape sequence '\W'
<>:12: SyntaxWarning: invalid escape sequence '\s'
<>:8: SyntaxWarning: invalid escape sequence '\s'
<>:9: SyntaxWarning: invalid escape sequence '\W'
<>:12: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_756/980243387.py:8: SyntaxWarning: invalid escape sequence '\s'
  s = re.sub('\s\W',' ',s)
/tmp/ipykernel_756/980243387.py:9: SyntaxWarning: invalid escape sequence '\W'
  s = re.sub('\W\s',' ',s)
/tmp/ipykernel_756/980243387.py:12: SyntaxWarning: invalid escape sequence '\s'
  s = re.sub('\s+',' ',s)

In [8]:
twigen.head()

    _unit_id  ...                                   description_norm
0  815719226  ...                              i sing my own rhythm.
1  815719227  ...  i'm the author of novels filled with family dr...
2  815719228  ...                louis whining and squealing and all
3  815719229  ...  mobile guy 49ers shazam google kleiner perkins...
4  815719230  ...  ricky wilson the best frontman/kaiser chiefs t...

[5 rows x 28 columns]

Let's grab some info about the gold standard and about the dataset's confidence in its gender classifications so we have some idea of what would be good to train on.

In [ ]:

# how many observations are gold standard?
# golden values(True,False) mean that the entry is 100% reliable and verified
# Source: https://www.geeksforgeeks.org/python/defaultdict-in-python/
gold_values = defaultdict(int)
for val in twigen._golden:
    gold_values[val] += 1
print(gold_values)

# what does the confidence look like?
print(np.any(np.isnan(twigen['gender:confidence'])))
# we've got at least one NaN, so let's remove
gender_confidence = twigen['gender:confidence'][np.where(np.invert(np.isnan(twigen['gender:confidence'])))[0]]
print(len(gender_confidence))
gender_nonones = gender_confidence[np.where(gender_confidence < 1)[0]]
print(len(gender_nonones))

defaultdict(<class 'int'>, {False: 20000, True: 50})
True
20024
6098

About 30% of the observations have less than 100% confidence in the gender classification, so we'll ignore those.

In [ ]:
twigen_confident = twigen[twigen['gender:confidence']==1]
twigen_confident.shape

(13926, 28)

Okay, now let's see how well a Naive Bayes classifier can do by just looking at the words in the randomly chosen tweet.

In [ ]:
# pull the data into vectors
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(twigen_confident['text_norm'])

encoder = LabelEncoder()
y = encoder.fit_transform(twigen_confident['gender'])

# split into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# take a look at the shape of each of these
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(11140, 33868)
(11140,)
(2786, 33868)
(2786,)

Alright, let's make the classifier

In [ ]:
nb = MultinomialNB()
nb.fit(x_train, y_train)

print(nb.score(x_test, y_test))

0.594041636755

So we get about 58% accuracy on the "best" observations, using only tweet text.

Let's try a couple more features. Specifically, let's add the description text by concatenating it to the tweet text.

In [ ]:
twigen['all_features'] = twigen['text_norm'].str.cat(twigen['description_norm'], sep=' ')

twigen_confident = twigen[twigen['gender:confidence']==1]

In [ ]:
# pull the data into vectors
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(twigen_confident['text_norm'])

encoder = LabelEncoder()
y = encoder.fit_transform(twigen_confident['gender'])

# split into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

nb = MultinomialNB()
nb.fit(x_train, y_train)

print(nb.score(x_test, y_test))

0.571428571429

Cool, so we gain about 2-3 percentage points in accuracy just by adding description text alongside tweet text.

You can use this kind of procedure to play around with adding more features, or try a different type of model and see how accurately you can predict gender. (Maybe also try including the less-confident observations; my exclusion of them was probably anti-conservative)